/*
 * This source file was generated by the Gradle 'init' task
 */
package lab5_test;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String getGreeting2() {
        return "Hello World2!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting2());
    }
}
